#Maintainer: Shivam Mudotia (shivam.mudotia@nagarro.com)
- name: Create EC2 instances
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ region_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    vpc_subnet_id: "{{ subnet_id }}"
    group: "{{ instance_name }}-sg"
    wait: yes
    instance_tags:
      Name: "{{ instance_name }}"
    count_tag: 
      Name: "{{ instance_name }}"
    exact_count: 1
    assign_public_ip: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2
  
- name: Add the newly created EC2 instance(s) to the local host group
  local_action: lineinfile 
                path="inventory/ec2"
                regexp={{ item.public_ip }} 
                insertafter="[servers]" line="{{ item.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ ec2.instances }}"


- name: Wait for SSH to come up
  local_action: wait_for 
      host={{ item.public_ip }} 
      port=22 
      state=started
  with_items: "{{ ec2.instances }}"


# - name: Create EC2 instances
#   amazon.aws.ec2_instance:
#     key_name: "{{ key_name }}"
#     region: "{{ region_name }}"
#     instance_type: "{{ instance_type }}"
#     image_id: "{{ ami_id }}"
#     vpc_subnet_id: "{{ subnet_id }}"
#     security_group: "{{ instance_name }}-sg"
#     wait: true
#     tags:
#       Name: "{{ instance_name }}"
#     exact_count: 1
#     network:
#       assign_public_ip: true
#     aws_access_key: "{{ aws_access_key }}"
#     aws_secret_key: "{{ aws_secret_key }}"
#     state: running
#   register: ec2


# - name: Add the newly created EC2 instance(s) to the local host group
#   local_action: lineinfile
#                 path="inventory/ec2"
#                 state=present
#                 regexp={{ item.public_ip_address }}
#                 insertafter="[servers]"
#                 line="{{ item.public_ip_address }} ansible_user=ubuntu ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
#   with_items: "{{ ec2.instances }}"


# - name: Wait for SSH to come up
#   local_action: wait_for
#                 host={{ item.public_ip_address }}
#                 port=22
#                 state=started
#   with_items: "{{ ec2.instances }}"