# Maintainer: Shivam Mudotia (shivam.mudotia@nagarro.com)
# Setup Networking components
- name: "Create Networking components"
  hosts: local
  vars_files:
    - ./vars/main.yml
  gather_facts: False
  roles:
    - role: 1-setup-networking