# Maintainer: Shivam Mudotia (shivam.mudotia@nagarro.com)
- name: "Terminate control host"
  ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region_name }}"
    state: absent
    filters:
      "tag:Name": "{{ instance_name }}"
  register: ec2

- name: Clean local EC2 inventory file
  local_action: lineinfile 
                path="inventory/ec2"
                regexp='ansible'
                state=absent
                # insertafter="[servers]" line="{{ item.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=keys/{{ key_name }}.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
  with_items: "{{ ec2.instances }}"