- name: Create EBS Volume for Prometheus
  amazon.aws.ec2_vol:
    volume_size: 10
    volume_type: gp2
    name: "perf-test_photon-prometheus"
    zone: "{{ region_name }}a"
    region: "{{ region_name }}"
    tags:
      kubernetes.io/cluster/perf-test_photon_eks_cluster:	"owned"
      kubernetes.io/created-for/pvc/namespace: "default"
      KubernetesCluster: "perf-test_photon_eks_cluster"
      ebs.csi.aws.com/cluster: "true"
  register: aws_ec2volume_prom

- name: Update the newly created prometheus volume ID to the local variables
  local_action: lineinfile 
                path="vars/main.yml"
                regexp='^prometheus_volume_id'
                line=prometheus_volume_id:{{ " " }}'{{ aws_ec2volume_prom.volume_id }}'
  with_items: "{{ aws_ec2volume_prom.volume_id }}"

- name: Update the newly created prometheus volume ID in framework-stack/terraform-eks/ReclaimPv_prometheus.yaml file
  local_action: lineinfile 
                path="framework-stack/terraform-eks/ReclaimPv_prometheus.yaml"
                regexp='^    volumeID'
                line='    volumeID:{{ " " }}{{ aws_ec2volume_prom.volume_id }}'
  with_items: "{{ aws_ec2volume_prom.volume_id }}"
